version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: omnicrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./infra/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  nats:
    image: nats:2
    ports:
      - '4222:4222'
  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-29Z
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
    volumes:
      - minio-data:/data
volumes:
  minio-data:
